from django.core.management.base import BaseCommand, CommandError
from django.core.management import call_command

class Command(BaseCommand):
    help = "Ejecuta todos los seeders del proyecto en orden (users ‚Üí catalog ‚Üí customers ‚Üí orders)"

    def handle(self, *args, **options):
        try:
            self.stdout.write(self.style.NOTICE("üöÄ Iniciando seeders de MotoParts..."))

            # 1Ô∏è‚É£ Usuarios (primero, porque los dem√°s dependen de esto)
            self.stdout.write(self.style.NOTICE("\n‚û°Ô∏è Cargando usuarios..."))
            call_command("seed_users")

              # 3Ô∏è‚É£ Clientes
            self.stdout.write(self.style.NOTICE("\n‚û°Ô∏è Cargando clientes..."))
            call_command("seed_customers")

            # 2Ô∏è‚É£ Cat√°logo (productos, marcas, categor√≠as)
            self.stdout.write(self.style.NOTICE("\n‚û°Ô∏è Cargando cat√°logo..."))
            call_command("seed_catalog")

          

            # 4Ô∏è‚É£ Pedidos
            # self.stdout.write(self.style.NOTICE("\n‚û°Ô∏è Cargando pedidos..."))
            # call_command("seed_orders")

            self.stdout.write(self.style.SUCCESS("\n‚úÖ Seeders ejecutados correctamente en orden."))

        except CommandError as e:
            self.stdout.write(self.style.ERROR(f"‚ùå Error al ejecutar seeders: {e}"))
